### ISSUE TITLE
How to run dhrystone benchmark on personal RV32

### ISSUE THREAD

**Issue by umer006** [Keith-S-Thompson/dhrystone#1]
I designed a RV32-IMC core, and i need to bnechmark my processor on dhrystone, how can i convert this .c file into a 32 bit instructions set that i can give to my processor and check its performance.

**Comment by Keith-S-Thompson** [comment]
Which .c file? I have several versions of Dhrystone in the repo.

Do you have a C compiler for your target system? There does seem to be a gcc RISC-V cross-compiler, but I've never used it.

This is very old code, written in an old version of the C language. I haven't looked at it in years. Just now, I was unable to compile it with gcc. The code could be modernized, but I haven't bothered to do so.

**Comment by umer006** [comment]
Sorry for the late reply,
I am kind of new at this, i coded a RV32 Processor which takes in instructions in the following manner;
03000513
00000097
000080e7
00050713
000007b7
00e7a023
03000513
00000097
000080e7
00050713
000007b7
00e7a023
000007b7
0007a783
00000737
00072703

The bin file contains string like these and then they are copied in the Instruction Memory of the Processor and then they are processed one by one, My instructor told me to run the Dhrystone benchmark on my processor, right now i have RISC-V GNU Compiler Toolchain, it can convert simple c program and i can take the above kind of dump from that, but it does not really convert c programs with functions in it very well, i was wondering if there was some way that i can convert the Dhrystone benchmark into the above kind of dump so that i can run it on my processor.

**Comment by Keith-S-Thompson** [comment]
You should use a newer version of Dhrystone (which I don't have in my repo):

https://homepages.cwi.nl/~steven/dry.c

The author updated it so it should work with modern C compilers.

The instructions at the top of the file say to do `sh dry.c`. The first few lines of the file are a shell script that extracts and compiles the C source. It compiles with `cc` by default (typically a symlink to `gcc`), but you can set the `CC` and `CFLAGS` environment variables.

The script compiles and run the code locally, which won't work for a cross-compiler. You'll need to modify the script and/or do some of the steps manually.

Presumably your toolchain is going to generate binary object code. Apparently you know how to get the numeric instructions you need from that.

**Comment by umer006** [comment]
Thanks man, I'll try that.
